const fs = require('fs');
const path = require('path');

const diseases = [
  {
    id: "disease-rice-blast",
    category: "disease",
    crop: "Paddy / Rice",
    topic: "Rice Blast",
    title: "Rice Blast (Dhaan ka Jhonka Rog)",
    title_hi: "धान का झोंका रोग (Rice Blast)",
    description: "Spindle-shaped lesions on leaves with grayish centers. Spreads rapidly in high humidity conditions.",
    description_hi: "पत्तियों पर आंख या नाव के आकार के धब्बे जिनके बीच का भाग स्लेटी होता है। अधिक नमी में तेजी से फैलता है।",
    metadata: {
      crop: "Paddy / Rice",
      confidence: "94%",
      severity: "High",
      symptoms: "Spindle-shaped lesions on leaves with grayish centers. Spreading rapidly due to high humidity.",
      symptoms_hi: "पत्तियों पर धब्बे, तने के जोड़ों का काला पड़ना, बालियों का सूखना।",
      organicTreatment: "Spray Neem oil formulation (3,000 ppm) at 3 ml per liter of water. Ensure proper spacing between rows.",
      organicTreatment_hi: "नीम तेल (3000 ppm) 3 मिली प्रति लीटर पानी में मिलाकर छिड़कें। ट्राइकोड्रामा 5 ग्राम/लीटर का प्रयोग करें।",
      chemicalTreatment: "Spray Tricyclazole 75 WP at 0.6 grams per liter of water. Avoid water logging.",
      chemicalTreatment_hi: "ट्राइसाइक्लाजोल 75 WP (0.6 ग्राम/लीटर) पानी में मिलाकर छिड़काव करें।",
      preventiveMeasures: "Destroy previous crop residues. Do not apply excessive nitrogen fertilizer.",
      preventiveMeasures_hi: "प्रमाणित बीजों का प्रयोग करें। यूरिया का अत्यधिक उपयोग न करें।",
      outbreakIndicator: "Reported in humid paddy regions during monsoon.",
      reportType: "Leaf Disease Scan",
      keywords: ["rice blast", "dhaan jhonka", "paddy leaf spot", "spindle lesions", "grey center spot"],
      keywords_hi: ["धान का झोंका", "धान ब्लास्ट", "पत्ती का धब्बा", "धान का रोग"],
      keywords_romanized: ["dhaan blast", "dhan jhonka", "paddy blast", "rice jhonka"]
    }
  },
  {
    id: "disease-rice-bacterial-blight",
    category: "disease",
    crop: "Paddy / Rice",
    topic: "Bacterial Leaf Blight",
    title: "Rice Bacterial Leaf Blight (Dhaan ka Jeevanu Jhulsa)",
    title_hi: "धान का जीवाणु झुलसा रोग (Bacterial Leaf Blight)",
    description: "Water-soaked lesions on leaf margins turning yellow to white with wavy borders.",
    description_hi: "पत्तियों के किनारों पर पानी से भीगे हुए धब्बे जो पीले और बाद में सफेद हो जाते हैं।",
    metadata: {
      crop: "Paddy / Rice",
      severity: "High",
      symptoms: "Yellowing and drying of leaves starting from tips along the margins.",
      symptoms_hi: "पत्तियों की नोक और किनारों से पीला पड़कर सूखना।",
      organicTreatment: "Spray fresh cow dung extract (20kg in 200L water) strained through cloth.",
      organicTreatment_hi: "ताजा गाय के गोबर का घोल (5%) छानकर छिड़काव करें।",
      chemicalTreatment: "Copper hydroxide 77 WP at 2g/L along with Streptocycline 0.15g/L.",
      chemicalTreatment_hi: "कॉपर हाइड्रॉक्साइड 2 ग्राम और स्ट्रैप्टोसाइक्लिन 0.15 ग्राम प्रति लीटर पानी।",
      preventiveMeasures: "Avoid excessive nitrogen fertilizers. Drain stagnant water.",
      preventiveMeasures_hi: "खेत से अतिरिक्त पानी निकालें। नाइट्रोजन सीमित मात्रा में दें।",
      keywords: ["bacterial leaf blight", "blb", "dhaan jhulsa", "leaf margin yellowing"],
      keywords_hi: ["जीवाणु झुलसा", "धान झुलसा", "पत्ती सूखना"],
      keywords_romanized: ["dhan jhulsa", "bacterial blight paddy", "patti sukhna"]
    }
  },
  {
    id: "disease-rice-sheath-blight",
    category: "disease",
    crop: "Paddy / Rice",
    topic: "Sheath Blight",
    title: "Rice Sheath Blight (Dhaan ka Sheath Blight)",
    title_hi: "धान का शीथ ब्लाइट रोग",
    description: "Oval or irregular greenish-grey spots on leaf sheaths near water level.",
    description_hi: "पानी की सतह के पास तने और पत्तियों के आवरण पर हरे-सफेद अंडे जैसे धब्बे।",
    metadata: {
      crop: "Paddy / Rice",
      severity: "Medium-High",
      symptoms: "Snake-skin like spots on leaf sheaths leading to lodging of crop.",
      symptoms_hi: "तने के निचले हिस्से पर सांप की त्वचा जैसे चकत्ते।",
      organicTreatment: "Spray Pseudomonas fluorescens at 10g/L on lower parts of stems.",
      organicTreatment_hi: "सुडोमोनास फ्लोरेसेंस 10 ग्राम प्रति लीटर पानी का छिड़काव तने के निचले भाग पर करें।",
      chemicalTreatment: "Hexaconazole 5 EC at 2 ml/L or Validamycin 3L at 2 ml/L.",
      chemicalTreatment_hi: "हेक्साकोनाज़ोल 5 EC (2 मिली/लीटर) या वैलिडामाइसिन का छिड़काव।",
      preventiveMeasures: "Maintain optimum plant spacing and balanced fertilization.",
      preventiveMeasures_hi: "पौधों के बीच उचित दूरी रखें और अत्यधिक यूरिया न डालें।",
      keywords: ["sheath blight", "dhaan sheath blight", "snake skin spot paddy"],
      keywords_hi: ["शीथ ब्लाइट", "धान का तना सड़न"],
      keywords_romanized: ["sheath blight dhaan", "tana sadan dhan"]
    }
  },
  {
    id: "disease-rice-brown-spot",
    category: "disease",
    crop: "Paddy / Rice",
    topic: "Brown Spot",
    title: "Rice Brown Spot (Dhaan ka Bhura Dhabba)",
    title_hi: "धान का भूरा धब्बा रोग (Brown Spot)",
    description: "Oval sesame seed shaped brown spots with yellow halos on leaves.",
    description_hi: "पत्तियों पर तिल के आकार के गोल भूरे धब्बे जिनके चारों ओर पीला घेरा होता है।",
    metadata: {
      crop: "Paddy / Rice",
      severity: "Medium",
      symptoms: "Numerous small oval brown spots on leaves and glumes indicating nutrient deficiency.",
      symptoms_hi: "पत्तियों और दानों पर छोटे भूरे धब्बे, पौधे कमजोर पड़ना।",
      organicTreatment: "Soil application of FYM and spray Trichoderma viride.",
      organicTreatment_hi: "गोबर की खाद डालें और ट्राइकोड्रामा विरिडी 5 ग्राम/लीटर का छिड़काव करें।",
      chemicalTreatment: "Mancozeb 75 WP at 2g/L or Zineb 75 WP at 2g/L.",
      chemicalTreatment_hi: "मैनकोज़ेब 75 WP (2 ग्राम/लीटर पानी) का छिड़काव करें।",
      preventiveMeasures: "Apply potash and micronutrients based on soil test recommendations.",
      preventiveMeasures_hi: "पोटाश और जिंक की संतुलित मात्रा दें।",
      keywords: ["brown spot rice", "dhaan bhura dhabba", "sesame leaf spot"],
      keywords_hi: ["भूरा धब्बा", "धान का भूरा रोग"],
      keywords_romanized: ["bhura dhabba dhaan", "rice brown spot"]
    }
  },
  {
    id: "disease-wheat-yellow-rust",
    category: "disease",
    crop: "Wheat",
    topic: "Yellow Rust",
    title: "Wheat Yellow Rust / Yellow Leaves (Gehun me Peeli Pattiyan)",
    title_hi: "गेहूं का पीला रतुआ / पीली पत्तियां (Yellow Rust)",
    description: "Yellow linear stripes of pustules on leaves during cold humid winter weather.",
    description_hi: "ठंड के मौसम में पत्तियों पर पीले रंग की कतारबद्ध धारियां और पीला पाउडर जमना।",
    metadata: {
      crop: "Wheat (Gehun)",
      severity: "High",
      symptoms: "Yellow powder stripes on leaves, leaf yellowing, reduced grain filling.",
      symptoms_hi: "पत्तियों पर पीली धारियां, छूने पर हाथ में पीला पाउडर लगना, पत्तियां पीली पड़ना।",
      organicTreatment: "Spray sour buttermilk (chaach) solution or Neem oil 3ml/L.",
      organicTreatment_hi: "खट्टी छाछ (5 लीटर/200 लीटर पानी) या नीम तेल का छिड़काव करें।",
      chemicalTreatment: "Propiconazole 25 EC at 1 ml per liter of water.",
      chemicalTreatment_hi: "प्रोपीकोनाज़ोल 25 EC (1 मिली प्रति लीटर पानी) का छिड़काव करें।",
      preventiveMeasures: "Grow rust-resistant varieties like HD-2967, DBW-187.",
      preventiveMeasures_hi: "रोगरोधी किस्मों जैसे HD-2967, DBW-187 की बुआई करें।",
      keywords: ["yellow rust wheat", "gehun peeli pattiyan", "stripe rust", "yellow powder leaves"],
      keywords_hi: ["पीला रतुआ", "गेहूं पीली पत्तियां", "गेहूं का पीला रोग"],
      keywords_romanized: ["gehu peeli patti", "peela ratua gehun", "yellow rust gehu"]
    }
  },
  {
    id: "disease-wheat-brown-rust",
    category: "disease",
    crop: "Wheat",
    topic: "Brown Rust",
    title: "Wheat Brown Rust / Leaf Rust (Gehun ka Bhura Ratua)",
    title_hi: "गेहूं का भूरा रतुआ (Brown Rust / Leaf Rust)",
    description: "Small orange-brown round pustules scattered randomly on leaf surfaces.",
    description_hi: "पत्तियों पर नारंगी-भूरे रंग के छोटे गोल चकत्ते जो बिखरे हुए दिखाई देते हैं।",
    metadata: {
      crop: "Wheat",
      severity: "Medium-High",
      symptoms: "Orange-brown powder on leaf surface leading to premature leaf drying.",
      symptoms_hi: "पत्तियों पर भूरा पाउडर जमना और पत्तियां समय से पहले सूखना।",
      organicTreatment: "Spray neem leaf extract and bio-fungicide Trichoderma.",
      organicTreatment_hi: "नीम की पत्ती का अर्क और ट्राइकोड्रामा 5 ग्राम/लीटर का प्रयोग करें।",
      chemicalTreatment: "Mancozeb 75 WP at 2g/L or Propiconazole 25 EC at 1 ml/L.",
      chemicalTreatment_hi: "मैनकोज़ेब 75 WP (2 ग्राम/लीटर) या प्रोपीकोनाज़ोल का छिड़काव करें।",
      preventiveMeasures: "Timely sowing and balanced NPK fertilizer application.",
      preventiveMeasures_hi: "समय पर बुआई करें और पोटाश की उचित मात्रा दें।",
      keywords: ["brown rust wheat", "gehun bhura ratua", "leaf rust orange pustules"],
      keywords_hi: ["भूरा रतुआ", "गेहूं भूरा रोग"],
      keywords_romanized: ["bhura ratua gehun", "wheat leaf rust"]
    }
  },
  {
    id: "disease-wheat-loose-smut",
    category: "disease",
    crop: "Wheat",
    topic: "Loose Smut",
    title: "Wheat Loose Smut (Gehun ka Khula Kangoiy / Kaala Churna)",
    title_hi: "गेहूं का खुला कगुआ / काला चूर्ण रोग (Loose Smut)",
    description: "Earheads transformed into black powdery mass of fungal spores.",
    description_hi: "गेहूं की बालियों में दाने की जगह काला चूर्ण भर जाता है।",
    metadata: {
      crop: "Wheat",
      severity: "High",
      symptoms: "Black soot-like powder in wheat earheads at flowering stage.",
      symptoms_hi: "बालियां निकलने पर दानों की जगह काला पाउडर दिखाई देना।",
      organicTreatment: "Solar heat seed treatment (soaking seeds in water for 4 hours in sun).",
      organicTreatment_hi: "सौर ऊर्जा उपचार: मई-जून की धूप में बीजों को पानी में भिगोकर सुखाएं।",
      chemicalTreatment: "Seed treatment with Carboxin 75 WP or Carbendazim 50 WP at 2g/kg seed.",
      chemicalTreatment_hi: "कारबॉक्सिन या कार्बेन्डाजिम (2 ग्राम प्रति किग्रा बीज) से बीज उपचार करें।",
      preventiveMeasures: "Always treat seeds before sowing.",
      preventiveMeasures_hi: "बीज उपचार के बिना बुआई कभी न करें।",
      keywords: ["loose smut wheat", "gehun kaala churna", "black powder wheat earhead"],
      keywords_hi: ["खुला कगुआ", "गेहूं का काला रोग", "काली बाली"],
      keywords_romanized: ["gehu loose smut", "kaala churna gehun"]
    }
  },
  {
    id: "disease-wheat-powdery-mildew",
    category: "disease",
    crop: "Wheat",
    topic: "Powdery Mildew",
    title: "Wheat Powdery Mildew (Gehun ka Safed Churna Rog)",
    title_hi: "गेहूं का सफेद चूर्ण रोग (Powdery Mildew)",
    description: "White cottony/powdery patches on leaves and stems.",
    description_hi: "पत्तियों और तनों पर सफेद रुई जैसा या चूर्ण जैसा पाउडर जमना।",
    metadata: {
      crop: "Wheat",
      severity: "Medium",
      symptoms: "White grey powdery growth covering leaves leading to yellowing and drying.",
      symptoms_hi: "पत्तियों पर सफेद पाउडर की परत चढ़ना, जिससे प्रकाश संश्लेषण रुकता है।",
      organicTreatment: "Spray sulfur-based organic formulation or cow urine solution (10%).",
      organicTreatment_hi: "गोमूत्र (10%) या घुलनशील सल्फर 3 ग्राम/लीटर का छिड़काव करें।",
      chemicalTreatment: "Wettable Sulfur 80 WP at 3g/L or Propiconazole 25 EC at 1 ml/L.",
      chemicalTreatment_hi: "घुलनशील सल्फर 80 WP (3 ग्राम/लीटर) पानी में मिलाकर छिड़कें।",
      preventiveMeasures: "Avoid dense sowing and heavy nitrogen doses.",
      preventiveMeasures_hi: "घनी बुआई न करें और हवा का प्रवाह बनाए रखें।",
      keywords: ["powdery mildew wheat", "gehun safed churna", "white powder wheat"],
      keywords_hi: ["सफेद चूर्ण", "गेहूं चूर्णी फफूंद"],
      keywords_romanized: ["safed churna gehun", "powdery mildew gehu"]
    }
  },
  {
    id: "disease-cotton-leaf-curl",
    category: "disease",
    crop: "Cotton",
    topic: "Leaf Curl Virus",
    title: "Cotton Leaf Curl (Kapas ka Patta Marod Rog)",
    title_hi: "कपास का पत्ता मरोड़ रोग (Cotton Leaf Curl)",
    description: "Upward curling of leaf margins, thick veins on leaves, stunted plant growth.",
    description_hi: "पत्तियों के किनारे ऊपर की ओर मुड़ना, नसें मोटी होना और पौधे का बौना रह जाना।",
    metadata: {
      crop: "Cotton",
      severity: "High",
      symptoms: "Upward curling of leaf margins, thick veins on leaves, stunted plant growth.",
      symptoms_hi: "पत्तियां ऊपर मुड़ना, नसों का उभरा होना, कपासी फल न बनना।",
      organicTreatment: "Introduce ladybird beetles to control whiteflies vector. Spray garlic-chili extract.",
      organicTreatment_hi: "सफेद मक्खी नियंत्रण के लिए नीम तेल 5 मिली/लीटर या लहसुन-मिर्च अर्क छिड़कें।",
      chemicalTreatment: "Spray Imidacloprid 17.8 SL at 0.5 ml per liter of water to control vector.",
      chemicalTreatment_hi: "इमिडाक्लोप्रिड 17.8 SL (0.5 मिली/लीटर) सफेद मक्खी नियंत्रण हेतु छिड़कें।",
      preventiveMeasures: "Use resistant cotton hybrids. Eliminate weed hosts near field bunds.",
      preventiveMeasures_hi: "प्रतिरोधी हाइब्रिड किस्मों का चयन करें और खरपतवार नष्ट करें।",
      keywords: ["cotton leaf curl", "kapas patta marod", "whitefly vector cotton"],
      keywords_hi: ["पत्ता मरोड़", "कपास पत्ती मुड़ना"],
      keywords_romanized: ["kapas patta marod", "cotton leaf curl"]
    }
  },
  {
    id: "disease-cotton-bacterial-blight",
    category: "disease",
    crop: "Cotton",
    topic: "Bacterial Blight",
    title: "Cotton Bacterial Blight / Black Arm (Kapas ka Black Arm)",
    title_hi: "कपास का जीवाणु झुलसा / ब्लैक आर्म रोग",
    description: "Angular water-soaked spots on leaves turning dark brown or black on veins.",
    description_hi: "पत्तियों पर कोणीय धब्बे तथा तनों पर काले धब्बे (ब्लैक आर्म) बनना।",
    metadata: {
      crop: "Cotton",
      severity: "Medium-High",
      symptoms: "Angular leaf spots, black lesions on stems causing branch breakage.",
      symptoms_hi: "पत्तियों पर कोणीय धब्बे और टहनियों का काला पड़कर टूटना।",
      organicTreatment: "Copper oxychloride + Neem oil spray.",
      organicTreatment_hi: "कॉपर ऑक्सीक्लोराइड 3 ग्राम/लीटर और नीम तेल का छिड़काव।",
      chemicalTreatment: "Copper Oxychloride 50 WP at 3g/L + Streptocycline at 0.1g/L.",
      chemicalTreatment_hi: "कॉपर ऑक्सीक्लोराइड 3 ग्राम + स्ट्रैप्टोसाइक्लिन 0.1 ग्राम प्रति लीटर।",
      preventiveMeasures: "Acid delinting of cotton seed before sowing.",
      preventiveMeasures_hi: "बीज का तेजाबी उपचार (Acid delinting) करें।",
      keywords: ["cotton bacterial blight", "black arm cotton", "kapas angular spot"],
      keywords_hi: ["ब्लैक आर्म", "कपास का जीवाणु रोग"],
      keywords_romanized: ["black arm kapas", "bacterial blight cotton"]
    }
  },
  {
    id: "disease-cotton-fusarium-wilt",
    category: "disease",
    crop: "Cotton",
    topic: "Fusarium Wilt",
    title: "Cotton Fusarium Wilt (Kapas ka Ukhata Rog)",
    title_hi: "कपास का उकठा / उखाड़ा रोग (Wilt)",
    description: "Yellowing and browning of leaves, wilting of plant from top to bottom.",
    description_hi: "पत्तियों का पीला पड़ना, मुरझाना और पौधे का सूख जाना। तना काटने पर अंदर काली धारी दिखती है।",
    metadata: {
      crop: "Cotton",
      severity: "High",
      symptoms: "Wilting of branches, internal vascular discoloration of stems.",
      symptoms_hi: "पौधे का अचानक मुरझाना, तने के अंदर भूरी-काली नसें दिखना।",
      organicTreatment: "Soil drenching with Trichoderma viride 10g/L.",
      organicTreatment_hi: "ट्राइकोड्रामा विरिडी 10 ग्राम/लीटर से जड़ों में ड्रेंचिंग करें।",
      chemicalTreatment: "Drench soil with Carbendazim 50 WP at 2g/L.",
      chemicalTreatment_hi: "कार्बेन्डाजिम 50 WP (2 ग्राम/लीटर) से जड़ों के पास सिंचाई करें।",
      preventiveMeasures: "Follow crop rotation with non-host crops like maize or sorghum.",
      preventiveMeasures_hi: "फसल चक्र अपनाएं, मक्का या ज्वार के बाद ही कपास बोएं।",
      keywords: ["cotton wilt", "kapas ukhata", "fusarium wilt cotton"],
      keywords_hi: ["उकठा रोग", "कपास सूखना"],
      keywords_romanized: ["kapas ukhata", "cotton wilt"]
    }
  },
  {
    id: "disease-tomato-early-blight",
    category: "disease",
    crop: "Tomato",
    topic: "Early Blight",
    title: "Early Blight (Tamatar Ageti Jhulsa)",
    title_hi: "टमाटर का अगेती झुलसा (Early Blight)",
    description: "Concentric dark brown circular spots appearing first on older leaves forming target board pattern.",
    description_hi: "निचली पत्तियों पर गोल भूरे धब्बे जिनमें छल्ले (Target board pattern) दिखाई देते हैं।",
    metadata: {
      crop: "Tomato",
      severity: "Medium",
      symptoms: "Concentric dark brown circular spots appearing first on older leaves.",
      symptoms_hi: "पत्तियों पर गोल छल्लेदार भूरे चकत्ते, पत्तियां पीली पड़कर गिरना।",
      organicTreatment: "Mulch soil surface with crop residue. Spray copper hydroxide or bio-pesticide Trichoderma.",
      organicTreatment_hi: "ट्राइकोड्रामा 5 ग्राम/लीटर या तांबे युक्त जैविक फफूंदनाशी का छिड़काव करें।",
      chemicalTreatment: "Spray Mancozeb 75 WP at 2 grams per liter of water immediately.",
      chemicalTreatment_hi: "मैनकोज़ेब 75 WP (2 ग्राम प्रति लीटर पानी) का तुरंत छिड़काव करें।",
      preventiveMeasures: "Ensure crop rotation. Water roots directly instead of overhead leaf sprinkling.",
      preventiveMeasures_hi: "फसल चक्र अपनाएं। पत्तियों पर ऊपर से पानी न छिड़कें।",
      keywords: ["tomato early blight", "tamatar ageti jhulsa", "target board leaf spot"],
      keywords_hi: ["अगेती झुलसा", "टमाटर झुलसा रोग"],
      keywords_romanized: ["tamatar ageti jhulsa", "tomato early blight"]
    }
  },
  {
    id: "disease-tomato-late-blight",
    category: "disease",
    crop: "Tomato",
    topic: "Late Blight",
    title: "Tomato Late Blight (Tamatar Pacheti Jhulsa)",
    title_hi: "टमाटर का पछेती झुलसा (Late Blight)",
    description: "Water-soaked dark lesions on leaves and fruits in cool wet weather.",
    description_hi: "ठंड और नमी में पत्तियों और फलों पर काले-भूरे धब्बे, सफेद फफूंद जमना।",
    metadata: {
      crop: "Tomato",
      severity: "High",
      symptoms: "Rapid rotting of foliage and brown patchy firm rot on tomato fruits.",
      symptoms_hi: "पत्तियों का रातों-रात झुलसना, फलों पर कठोर भूरे सड़े धब्बे।",
      organicTreatment: "Spray copper oxychloride or Bordeaux mixture (1%).",
      organicTreatment_hi: "बोर्डो मिश्रण (1%) या कॉपर ऑक्सीक्लोराइड 3 ग्राम/लीटर का छिड़काव।",
      chemicalTreatment: "Cymoxanil + Mancozeb at 2g/L or Metalaxyl + Mancozeb at 2g/L.",
      chemicalTreatment_hi: "मैटालेक्सिल + मैनकोज़ेब (2 ग्राम/लीटर पानी) का छिड़काव करें।",
      preventiveMeasures: "Avoid free moisture on leaf surface, plant in well-drained soil.",
      preventiveMeasures_hi: "खेत में पानी रुकने न दें, ठंड में रात को सिंचाई न करें।",
      keywords: ["tomato late blight", "tamatar pacheti jhulsa", "fruit rot tomato"],
      keywords_hi: ["पछेती झुलसा", "टमाटर सड़ांध"],
      keywords_romanized: ["tamatar pacheti jhulsa", "late blight tomato"]
    }
  },
  {
    id: "disease-tomato-leaf-curl",
    category: "disease",
    crop: "Tomato",
    topic: "Leaf Curl Virus",
    title: "Tomato Leaf Curl Virus (Tamatar Patti Marod Rog)",
    title_hi: "टमाटर का पत्ती मरोड़ रोग (Tomato Leaf Curl Virus)",
    description: "Severe curling, puckering, yellowing of leaves and bushy stunted appearance.",
    description_hi: "पत्तियों का अत्यधिक मुड़ना (मरोड़िया), छोटा होना, पीला पड़ना और पौधा झाड़ी जैसा बनना।",
    metadata: {
      crop: "Tomato",
      severity: "High",
      symptoms: "Upward or downward curling of tomato leaves, bushy plant, small fruit size.",
      symptoms_hi: "टमाटर की पत्तियां मुड़ना (leaf curl/mudna), पौधा छोटा रहना, फल न लगना।",
      organicTreatment: "Install yellow sticky traps (15/acre). Spray neem oil 5ml/L to clear whiteflies.",
      organicTreatment_hi: "पीले चिपचिपे कार्ड लगाएं। नीम तेल 5 मिली/लीटर का छिड़काव करें।",
      chemicalTreatment: "Dimethoate 30 EC at 1.5 ml/L or Imidacloprid 17.8 SL at 0.5 ml/L.",
      chemicalTreatment_hi: "इमिडाक्लोप्रिड 17.8 SL (0.5 मिली/लीटर) का सफेद मक्खी नियंत्रण हेतु छिड़काव करें।",
      preventiveMeasures: "Raise nurseries under insect-proof net covers.",
      preventiveMeasures_hi: "नर्सरी को नेट से ढककर उगाएं।",
      keywords: ["tomato leaf curl", "tamatar patti marod", "tamatar mudna", "curling tomato leaves"],
      keywords_hi: ["पत्ती मरोड़", "टमाटर पत्ती मुड़ना", "मरोड़िया रोग"],
      keywords_romanized: ["tamatar pattiyan mud rahi", "tamatar leaf curl", "patti marod tamatar"]
    }
  },
  {
    id: "disease-potato-early-blight",
    category: "disease",
    crop: "Potato",
    topic: "Early Blight",
    title: "Potato Early Blight (Aalu Ageti Jhulsa)",
    title_hi: "आलू का अगेती झुलसा (Early Blight)",
    description: "Brown angular spots with concentric rings on lower potato leaves.",
    description_hi: "आलू की निचली पत्तियों पर भूरे कोणीय धब्बे जिनमें गोल घेरे बनते हैं।",
    metadata: {
      crop: "Potato",
      severity: "Medium",
      symptoms: "Target board dark spots on lower leaves spreading to upper leaves.",
      symptoms_hi: "पत्तियों पर भूरे चकत्ते, समय से पहले पौधा पीला पड़ना।",
      organicTreatment: "Spray Trichoderma viride 5g/L or copper fungicides.",
      organicTreatment_hi: "ट्राइकोड्रामा विरिडी 5 ग्राम/लीटर का छिड़काव करें।",
      chemicalTreatment: "Mancozeb 75 WP at 2g/L or Chlorothalonil at 2g/L.",
      chemicalTreatment_hi: "मैनकोज़ेब 75 WP (2 ग्राम/लीटर) पानी में घोलकर छिड़कें।",
      preventiveMeasures: "Use healthy certified seed tubers and rotate crops.",
      preventiveMeasures_hi: "स्वस्थ आलू बीज का चयन करें।",
      keywords: ["potato early blight", "aalu ageti jhulsa", "potato leaf spot"],
      keywords_hi: ["अगेती झुलसा आलू", "आलू का रोग"],
      keywords_romanized: ["aalu ageti jhulsa", "potato early blight"]
    }
  },
  {
    id: "disease-potato-late-blight",
    category: "disease",
    crop: "Potato",
    topic: "Late Blight",
    title: "Potato Late Blight (Aalu Pacheti Jhulsa)",
    title_hi: "आलू का पछेती झुलसा (Late Blight)",
    description: "Water-soaked dark lesions on leaf tips/margins turning necrotic in foggy cloudy weather.",
    description_hi: "कोहरे और नमी में पत्तियों के किनारों पर पानी जैसे धब्बे जो तेजी से काले पड़कर पूरे खेत को सुखा देते हैं।",
    metadata: {
      crop: "Potato",
      severity: "High",
      symptoms: "Rapid foliage destruction, foul smell in field, tuber rot.",
      symptoms_hi: "पत्तियों का काला पड़कर गलना, खेत में बदबू आना, कंद सड़ना।",
      organicTreatment: "Bordeaux mixture (1%) spray before appearance of fog.",
      organicTreatment_hi: "बोर्डो मिश्रण (1%) का अग्रिम छिड़काव करें।",
      chemicalTreatment: "Mancozeb 75 WP (2g/L) preventively; Metalaxyl + Mancozeb (2g/L) curatively.",
      chemicalTreatment_hi: "मैनकोज़ेब 2 ग्राम/लीटर अग्रिम छिड़काव, या मैटालेक्सिल + मैनकोज़ेब 2 ग्राम/लीटर।",
      preventiveMeasures: "Destroy infected vines before harvest. Earthing up to protect tubers.",
      preventiveMeasures_hi: "मिट्टी अच्छी तरह चढ़ाएं ताकि कंद तक फफूंद न पहुंचे।",
      keywords: ["potato late blight", "aalu pacheti jhulsa", "potato foliage rot", "fog potato disease"],
      keywords_hi: ["पछेती झुलसा आलू", "आलू का सड़न रोग"],
      keywords_romanized: ["aalu pacheti jhulsa", "potato late blight"]
    }
  },
  {
    id: "disease-chilli-leaf-curl",
    category: "disease",
    crop: "Chilli",
    topic: "Leaf Curl Virus",
    title: "Chilli Leaf Curl Virus (Mirch Patti Marod / Churda Murda)",
    title_hi: "मिर्च का पत्ती मरोड़ / चुरड़ा-मुड़ड़ा रोग",
    description: "Leaves curl upwards, shrink in size, and plants become severely stunted.",
    description_hi: "मिर्च की पत्तियां ऊपर की ओर मुड़ती हैं (नौकाकार), छोटी हो जाती हैं और पौधा बौना रह जाता है।",
    metadata: {
      crop: "Chilli",
      severity: "High",
      symptoms: "Upward leaf curling, vein clearing, reduced flowering and fruit setting.",
      symptoms_hi: "मिर्च पत्ती मुड़ना (mirch pattiyan mudna), नाव की तरह मुड़ना, फूल गिरना।",
      organicTreatment: "Spray Neem oil 5ml/L + sour buttermilk (chaach) 50ml/L.",
      organicTreatment_hi: "नीम तेल 5 मिली + खट्टी छाछ 50 मिली प्रति लीटर पानी का छिड़काव।",
      chemicalTreatment: "Imidacloprid 17.8 SL at 0.5 ml/L or Fipronil 5 SC at 1.5 ml/L.",
      chemicalTreatment_hi: "इमिडाक्लोप्रिड 17.8 SL (0.5 मिली/लीटर) या फिप्रोनिल छिड़कें।",
      preventiveMeasures: "Control whiteflies and thrips early in the season.",
      preventiveMeasures_hi: "सफेद मक्खी और थ्रिप्स का शुरुआती दौर में ही नियंत्रण करें।",
      keywords: ["chilli leaf curl", "mirch patti marod", "churda murda mirch", "mirch mudna"],
      keywords_hi: ["चुरड़ा मुड़ड़ा", "मिर्च पत्ती मुड़ना", "मिर्च का मरोड़िया"],
      keywords_romanized: ["mirch pattiyan mud rahi", "mirch patti marod", "chilli leaf curl"]
    }
  },
  {
    id: "disease-chilli-anthracnose",
    category: "disease",
    crop: "Chilli",
    topic: "Anthracnose / Dieback",
    title: "Chilli Anthracnose / Fruit Rot / Dieback (Mirch Anthracnose / Phal Sadan)",
    title_hi: "मिर्च का फल सड़न / डाइबैक रोग (Anthracnose)",
    description: "Circular sunken spots on green/ripe chilli fruits and drying of twigs from top downwards.",
    description_hi: "मिर्च के फलों पर गोल धंसे हुए धब्बे और टहनियों का ऊपर से नीचे की ओर सूखना (Dieback)।",
    metadata: {
      crop: "Chilli",
      severity: "High",
      symptoms: "Sunken spots on chilli pods with black concentric rings, twig dieback.",
      symptoms_hi: "मिर्च के फलों पर काले दाग, फलों का सड़कर गिरना, टहनियां ऊपर से सूखना।",
      organicTreatment: "Spray Trichoderma harzianum or Neem oil formulation.",
      organicTreatment_hi: "ट्राइकोड्रामा 5 ग्राम/लीटर का छिड़काव करें।",
      chemicalTreatment: "Azoxystrobin 23 SC at 1 ml/L or Copper Oxychloride at 3g/L.",
      chemicalTreatment_hi: "एज़ोक्सीस्ट्रोबिन 23 SC (1 मिली/लीटर) या कॉपर ऑक्सीक्लोराइड 3 ग्राम/लीटर।",
      preventiveMeasures: "Seed treatment with Thiram 3g/kg seed. Remove dried twigs.",
      preventiveMeasures_hi: "बीज उपचार करें और सूखी टहनियों को काटकर नष्ट करें।",
      keywords: ["chilli anthracnose", "mirch dieback", "chilli fruit rot", "mirch phal sadan"],
      keywords_hi: ["फल सड़न", "डाइबैक मिर्च", "मिर्च का दाग रोग"],
      keywords_romanized: ["mirch anthracnose", "chilli dieback", "mirch fruit rot"]
    }
  },
  {
    id: "disease-brinjal-little-leaf",
    category: "disease",
    crop: "Brinjal",
    topic: "Little Leaf Disease",
    title: "Brinjal Little Leaf Disease (Baingan Chhoti Patti Rog)",
    title_hi: "बैंगन का छोटी पत्ती रोग (Little Leaf of Brinjal)",
    description: "Phytoplasma disease causing leaves to become extremely small, yellow, and crowded like a bush.",
    description_hi: "पत्तियां अत्यधिक छोटी, पतली और झाड़ीनुमा गुच्छे के रूप में बदल जाती हैं। फल नहीं बनते।",
    metadata: {
      crop: "Brinjal",
      severity: "High",
      symptoms: "Reduction in leaf size, bushy growth, sterility of flowers.",
      symptoms_hi: "पत्तियों का बहुत छोटा होना, पौधा झाड़ी बनना, फल न आना।",
      organicTreatment: "Uproot infected plants. Spray Neem oil 5ml/L to suppress leafhoppers.",
      organicTreatment_hi: "रोगी पौधों को उखाड़कर नष्ट करें। नीम तेल 5 मिली/लीटर का छिड़काव करें।",
      chemicalTreatment: "Dimethoate 30 EC at 1.5 ml/L to control leafhopper vector.",
      chemicalTreatment_hi: "लीफहॉपर नियंत्रण के लिए डाइमेथोएट 30 EC (1.5 मिली/लीटर) छिड़कें।",
      preventiveMeasures: "Remove weed hosts near brinjal plots.",
      preventiveMeasures_hi: "आस-पास के खरपतवार नष्ट करें।",
      keywords: ["brinjal little leaf", "baingan chhoti patti", "brinjal bush disease"],
      keywords_hi: ["छोटी पत्ती बैंगन", "बैंगन रोग"],
      keywords_romanized: ["baingan chhoti patti", "brinjal little leaf"]
    }
  },
  {
    id: "disease-okra-yellow-vein-mosaic",
    category: "disease",
    crop: "Okra",
    topic: "Yellow Vein Mosaic Virus",
    title: "Okra Yellow Vein Mosaic Virus (Bhindi Peeli Shira Mosaic)",
    title_hi: "भिंडी का पीला शिरा मोज़ेक रोग (Yellow Vein Mosaic)",
    description: "Veins of okra leaves turn bright yellow while interveinal areas remain green.",
    description_hi: "भिंडी की पत्तियों की नसें पीली हो जाती हैं और पूरा पत्ता पीला-हरा हो जाता है।",
    metadata: {
      crop: "Okra / Bhindi",
      severity: "High",
      symptoms: "Yellowing of leaf veins, pale green fruits, stunted growth.",
      symptoms_hi: "पत्तियों की नसें पीली पड़ना, फल पीले और कठोर होना।",
      organicTreatment: "Spray Neem oil (3,000 ppm) at 5ml/L to manage whitefly vector.",
      organicTreatment_hi: "नीम तेल 5 मिली/लीटर का सफेद मक्खी नियंत्रण हेतु छिड़काव करें।",
      chemicalTreatment: "Imidacloprid 17.8 SL at 0.5 ml/L or Thiamethoxam 25 WG at 0.3g/L.",
      chemicalTreatment_hi: "इमिडाक्लोप्रिड 17.8 SL (0.5 मिली/लीटर) का छिड़काव करें।",
      preventiveMeasures: "Grow YVMV resistant varieties like Arka Anamika, Parbhani Kranti.",
      preventiveMeasures_hi: "प्रतिरोधी किस्मों जैसे अर्क अनामिका, परभणी क्रांति की बुआई करें।",
      keywords: ["okra yellow vein mosaic", "bhindi peeli shira", "bhindi yellowing"],
      keywords_hi: ["पीला शिरा मोज़ेक", "भिंडी पीली पड़ना"],
      keywords_romanized: ["bhindi peeli patti", "okra yellow vein mosaic"]
    }
  },
  {
    id: "disease-mustard-alternaria-blight",
    category: "disease",
    crop: "Mustard",
    topic: "Alternaria Blight",
    title: "Mustard Alternaria Blight (Sarson Alternaria Jhulsa)",
    title_hi: "सरसों का अल्टरनेरिया झुलसा रोग",
    description: "Concentric dark brown circular spots on lower leaves, stems, and pods.",
    description_hi: "पत्तियों, तनों और फलियों पर काले-भूरे गोल छल्लेदार धब्बे।",
    metadata: {
      crop: "Mustard / Sarson",
      severity: "High",
      symptoms: "Black target board spots on pods causing premature shattering and low oil yield.",
      symptoms_hi: "फलियों पर काले धब्बे, समय से पहले दाना गिरना, तेल प्रतिशत घटना।",
      organicTreatment: "Spray Garlic leaf extract (5%) or Neem oil 3ml/L.",
      organicTreatment_hi: "लहसुन अर्क (5%) या नीम तेल 3 मिली/लीटर का छिड़काव।",
      chemicalTreatment: "Mancozeb 75 WP at 2g/L or Iprodione 50 WP at 2g/L.",
      chemicalTreatment_hi: "मैनकोज़ेब 75 WP (2 ग्राम प्रति लीटर पानी) का छिड़काव करें।",
      preventiveMeasures: "Sow mustard early (by mid-October) to escape blight outbreak.",
      preventiveMeasures_hi: "15 अक्टूबर तक अगेती बुआई करके रोग से बचें।",
      keywords: ["mustard alternaria blight", "sarson jhulsa", "mustard pod spot"],
      keywords_hi: ["अल्टरनेरिया झुलसा", "सरसों झुलसा"],
      keywords_romanized: ["sarson jhulsa", "mustard alternaria"]
    }
  },
  {
    id: "disease-mustard-white-rust",
    category: "disease",
    crop: "Mustard",
    topic: "White Rust",
    title: "Mustard White Rust (Sarson Safed Ratua / Safed Dhabba)",
    title_hi: "सरसों का सफेद रतुआ (White Rust)",
    description: "White or cream-colored raised pustules on the lower surface of leaves.",
    description_hi: "पत्तियों की निचली सतह पर सफेद रंग के फफोले (Pustules) जमना और फूल विकृत होना (Staghead).",
    metadata: {
      crop: "Mustard",
      severity: "High",
      symptoms: "White pustules on leaves, floral malformation into swollen stagheads.",
      symptoms_hi: "पत्तियों के नीचे सफेद धब्बे, फूलों का सूजकर विकृत होना।",
      organicTreatment: "Spray Trichoderma viride 5g/L + Neem oil 3ml/L.",
      organicTreatment_hi: "ट्राइकोड्रामा 5 ग्राम/लीटर और नीम तेल का छिड़काव।",
      chemicalTreatment: "Metalaxyl 8% + Mancozeb 64% WP at 2g/L.",
      chemicalTreatment_hi: "मैटालेक्सिल + मैनकोज़ेब (2 ग्राम/लीटर) पानी में मिलाकर छिड़कें।",
      preventiveMeasures: "Use clean seed and practice crop rotation.",
      preventiveMeasures_hi: "स्वस्थ बीजों की बुआई करें और फसल चक्र अपनाएं।",
      keywords: ["mustard white rust", "sarson safed ratua", "staghead mustard"],
      keywords_hi: ["सफेद रतुआ", "सरसों का सफेद रोग"],
      keywords_romanized: ["sarson safed ratua", "white rust mustard"]
    }
  },
  {
    id: "disease-chickpea-fusarium-wilt",
    category: "disease",
    crop: "Chickpea",
    topic: "Fusarium Wilt",
    title: "Chickpea Fusarium Wilt (Chana Ukhata Rog)",
    title_hi: "चने का उकठा रोग (Fusarium Wilt)",
    description: "Drooping of petioles and leaves, wilting of whole plant at flowering stage.",
    description_hi: "पत्तियों का झुकना, पीला पड़ना और पौधा जड़ से सूख जाना।",
    metadata: {
      crop: "Chickpea / Chana",
      severity: "High",
      symptoms: "Internal xylem dark discoloration in taproot, sudden wilting in patches.",
      symptoms_hi: "पौधों का पैच में सूखना, मुख्य जड़ को चीरने पर अंदर काली धारी।",
      organicTreatment: "Seed treatment with Trichoderma viride 10g/kg seed.",
      organicTreatment_hi: "ट्राइकोड्रामा विरिडी (10 ग्राम/किग्रा बीज) से बीज उपचार करें।",
      chemicalTreatment: "Seed treatment with Carbendazim 12% + Mancozeb 63% WP at 2g/kg seed.",
      chemicalTreatment_hi: "कार्बेन्डाजिम + मैनकोज़ेब (2 ग्राम/किग्रा) से बीज उपचार।",
      preventiveMeasures: "Deep summer plowing and crop rotation with sorghum or wheat.",
      preventiveMeasures_hi: "गर्मियों में गहरी जुताई करें। ज्वार या गेहूं के साथ फसल चक्र अपनाएं।",
      keywords: ["chickpea wilt", "chana ukhata", "fusarium wilt chana"],
      keywords_hi: ["चने का उकठा", "चना सूखना"],
      keywords_romanized: ["chana ukhata", "chickpea wilt"]
    }
  },
  {
    id: "disease-pigeonpea-wilt",
    category: "disease",
    crop: "Pigeon Pea",
    topic: "Fusarium Wilt",
    title: "Pigeon Pea Fusarium Wilt (Arhar/Tur Ukhata Rog)",
    title_hi: "अरहर का उकठा रोग (Fusarium Wilt)",
    description: "Gradual yellowing and wilting of branches leading to death of entire bush.",
    description_hi: "अरहर की शाखाओं का धीरे-धीरे पीला पड़ना और पूरा पौधा सूख जाना।",
    metadata: {
      crop: "Pigeon Pea / Arhar / Tur",
      severity: "High",
      symptoms: "Purple brown band on main stem near soil line, dark vascular bundles.",
      symptoms_hi: "तने की छाल पर नीली-काली धारी बनना, पौधे का सूख जाना।",
      organicTreatment: "Trichoderma viride 2.5 kg/acre mixed with FYM applied to soil.",
      organicTreatment_hi: "ट्राइकोड्रामा 2.5 किग्रा/एकड़ गोबर की खाद में मिलाकर खेत में डालें।",
      chemicalTreatment: "Drench roots with Carbendazim at 2g/L.",
      chemicalTreatment_hi: "कार्बेन्डाजिम (2 ग्राम/लीटर) से जड़ों के पास ड्रेंचिंग करें।",
      preventiveMeasures: "Sow wilt resistant varieties like Asha (BDN-2), Maruti (ICP-8863).",
      preventiveMeasures_hi: "प्रतिरोधी किस्मों जैसे आशा (BDN-2), मारुति (ICP-8863) की बुआई करें।",
      keywords: ["pigeonpea wilt", "arhar ukhata", "tur wilt"],
      keywords_hi: ["अरहर उकठा", "तुअर सूखना"],
      keywords_romanized: ["arhar ukhata", "tur wilt"]
    }
  },
  {
    id: "disease-sugarcane-red-rot",
    category: "disease",
    crop: "Sugarcane",
    topic: "Red Rot",
    title: "Sugarcane Red Rot (Ganna Laal Galan / Cancer Rog)",
    title_hi: "गन्ने का लाल सड़न रोग (Red Rot / Cancer Rog)",
    description: "Third and fourth leaves wither; split cane reveals reddened internal tissue with white cross bands and alcohol smell.",
    description_hi: "गन्ने के अंदर का भाग लाल हो जाता है जिसमें सफेद आड़ी धारियां और सिरके जैसी गंध आती है।",
    metadata: {
      crop: "Sugarcane / Ganna",
      severity: "High",
      symptoms: "Drying of cane crown, red color inside cane with white cross bands.",
      symptoms_hi: "गन्ने का ऊपरी हिस्सा सूखना, गन्ने को बीच से चीरने पर लाल रंग और सिरके की गंध।",
      organicTreatment: "Sett treatment with Trichoderma viride.",
      organicTreatment_hi: "ट्राइकोड्रामा 10 ग्राम/लीटर घोल में गन्ने के टुकड़ों को डुबोकर बोएं।",
      chemicalTreatment: "Sett treatment with Carbendazim 50 WP at 2g/L water for 15 mins.",
      chemicalTreatment_hi: "कार्बेन्डाजिम (2 ग्राम/लीटर) में 15 मिनट गन्ने के टुकड़े भिगोएं।",
      preventiveMeasures: "Use healthy setts, avoid rattoning infected fields.",
      preventiveMeasures_hi: "रोगी खेत की पेड़ी फसल (Ratoon) न लें।",
      keywords: ["sugarcane red rot", "ganna laal galan", "sugarcane cancer"],
      keywords_hi: ["लाल सड़न", "गन्ना कैंसर", "गन्ने का लाल रोग"],
      keywords_romanized: ["ganna laal galan", "sugarcane red rot"]
    }
  },
  {
    id: "disease-banana-sigatoka",
    category: "disease",
    crop: "Banana",
    topic: "Sigatoka Leaf Spot",
    title: "Banana Sigatoka Leaf Spot (Kela Sigatoka Dhabba)",
    title_hi: "केले का सिगाटोका पत्ती धब्बा रोग",
    description: "Yellowish green spots on leaves enlarging into dark brown spots with grey centers.",
    description_hi: "केले की पत्तियों पर पीले-हरे धब्बे जो बाद में भूरे-काले होकर पूरे पत्ते को सुखा देते हैं।",
    metadata: {
      crop: "Banana / Kela",
      severity: "High",
      symptoms: "Large necrotic leaf spots reducing photosynthetic area and bunch size.",
      symptoms_hi: "पत्तियों का समय से पहले सूखना, केले के घौंद (Bunch) का छोटा रह जाना।",
      organicTreatment: "Remove infected leaves. Spray mineral oil or Neem oil 5ml/L.",
      organicTreatment_hi: "रोगी पत्तियों को काटकर जलाएं। नीम तेल 5 मिली/लीटर का छिड़काव करें।",
      chemicalTreatment: "Propiconazole 25 EC at 1 ml/L or Carbendazim at 1g/L with sticker.",
      chemicalTreatment_hi: "प्रोपीकोनाज़ोल 25 EC (1 मिली/लीटर) चिपकने वाले पदार्थ (Sticker) के साथ छिड़कें।",
      preventiveMeasures: "Provide proper field drainage and maintain plant spacing.",
      preventiveMeasures_hi: "केले के बाग में जल निकासी का उत्तम प्रबंध रखें।",
      keywords: ["banana sigatoka", "kela leaf spot", "banana brown leaf spot"],
      keywords_hi: ["सिगाटोका", "केले का पत्ती धब्बा"],
      keywords_romanized: ["kela sigatoka", "banana leaf spot"]
    }
  },
  {
    id: "disease-mango-anthracnose",
    category: "disease",
    crop: "Mango",
    topic: "Anthracnose",
    title: "Mango Anthracnose (Aam Anthracnose / Kaala Dhabba)",
    title_hi: "आम का एंथ्रेक्नोज / काला धब्बा रोग",
    description: "Dark brown/black spots on leaves, flower panicles, and developing fruits.",
    description_hi: "आम के पत्तों, बौर (Panicles) और छोटे टिकोरों पर काले-भूरे धब्बे बनना और बौर का झड़ना।",
    metadata: {
      crop: "Mango / Aam",
      severity: "High",
      symptoms: "Blossom blight, premature drop of young fruits, black tear stains on mature fruit.",
      symptoms_hi: "बौर का झुलसकर गिरना, फलों पर काले धब्बे और सड़ांध।",
      organicTreatment: "Prune affected dried twigs. Spray Copper Oxychloride at 3g/L.",
      organicTreatment_hi: "सूखी टहनियों की छंटाई करें। कॉपर ऑक्सीक्लोराइड 3 ग्राम/लीटर छिड़कें।",
      chemicalTreatment: "Carbendazim 50 WP at 1g/L or Azoxystrobin 23 SC at 1 ml/L.",
      chemicalTreatment_hi: "कार्बेन्डाजिम (1 ग्राम/लीटर) बौर आने से पहले और बाद में छिड़कें।",
      preventiveMeasures: "Keep orchard clean, burn fallen leaves.",
      preventiveMeasures_hi: "बाग की साफ-सफाई रखें और गिरी पत्तियों को जलाएं।",
      keywords: ["mango anthracnose", "aam kaala dhabba", "blossom blight mango"],
      keywords_hi: ["एंथ्रेक्नोज आम", "आम का बौर झुलसा"],
      keywords_romanized: ["aam anthracnose", "mango blossom blight"]
    }
  },
  {
    id: "disease-mango-powdery-mildew",
    category: "disease",
    crop: "Mango",
    topic: "Powdery Mildew",
    title: "Mango Powdery Mildew (Aam ka Safed Churna Rog)",
    title_hi: "आम का चूर्णी आसिता / सफेद चूर्ण रोग (Powdery Mildew)",
    description: "White powdery fungal growth covering flower panicles, leaves, and young fruits.",
    description_hi: "आम के बौर और छोटे फलों पर सफेद पाउडर जम जाता है जिससे बौर सूखकर गिर जाता है।",
    metadata: {
      crop: "Mango",
      severity: "High",
      symptoms: "White powdery deposit on inflorescence causing heavy fruit drop.",
      symptoms_hi: "बौर पर सफेद चूर्ण जमना, पूरे बौर का सूखकर गिरना।",
      organicTreatment: "Spray Wettable Sulfur at 3g/L or Cow urine solution 10%.",
      organicTreatment_hi: "घुलनशील सल्फर 3 ग्राम/लीटर या 10% गोमूत्र का छिड़काव करें।",
      chemicalTreatment: "Hexaconazole 5 EC at 1 ml/L or Karathane at 1 ml/L.",
      chemicalTreatment_hi: "हेक्साकोनाज़ोल 5 EC (1 मिली/लीटर) बौर निकलते समय छिड़कें।",
      preventiveMeasures: "Spray preventively at mustard-stage of fruit setting.",
      preventiveMeasures_hi: "सरसों के दाने जितने टिकोरे बनने पर अग्रिम छिड़काव करें।",
      keywords: ["mango powdery mildew", "aam safed churna", "mango flower drop"],
      keywords_hi: ["चूर्णी आसिता", "आम का सफेद रोग"],
      keywords_romanized: ["aam powdery mildew", "aam safed churna"]
    }
  },
  {
    id: "disease-citrus-canker",
    category: "disease",
    crop: "Citrus",
    topic: "Citrus Canker",
    title: "Citrus Canker (Nimbu Canker / Khajli Rog)",
    title_hi: "नींबू का कैंकर रोग (Citrus Canker)",
    description: "Raised corky brown lesions on leaves, twigs, and lemon fruits surrounded by yellow halo.",
    description_hi: "नींबू की पत्तियों और फलों पर उभरे हुए खुरदरे भूरे दाने जिन पर पीला घेरा होता है।",
    metadata: {
      crop: "Citrus / Nimbu",
      severity: "High",
      symptoms: "Rough corky lesions on citrus leaves and rind causing unmarketable fruit quality.",
      symptoms_hi: "फलों की छाल खुरदरी और बदरंग होना, पत्तियां झड़ना।",
      organicTreatment: "Prune affected twigs and spray Neem cake extract.",
      organicTreatment_hi: "ग्रसित टहनियों को काटकर नष्ट करें। तांबे युक्त जैविक फफूंदनाशी का छिड़काव।",
      chemicalTreatment: "Copper Oxychloride 50 WP at 3g/L + Streptocycline at 0.1g/L.",
      chemicalTreatment_hi: "कॉपर ऑक्सीक्लोराइड 3 ग्राम + स्ट्रैप्टोसाइक्लिन 0.1 ग्राम/लीटर छिड़कें।",
      preventiveMeasures: "Control leaf miner pest which spreads canker bacteria.",
      preventiveMeasures_hi: "लीफ माइनर कीट का शुरुआती नियंत्रण करें।",
      keywords: ["citrus canker", "nimbu canker", "corky fruit spot lemon"],
      keywords_hi: ["कैंकर रोग", "नींबू कैंकर"],
      keywords_romanized: ["nimbu canker", "citrus canker"]
    }
  },
  {
    id: "disease-pomegranate-bacterial-blight",
    category: "disease",
    crop: "Pomegranate",
    topic: "Bacterial Blight",
    title: "Pomegranate Bacterial Blight / Teliya (Anar Teliya Rog)",
    title_hi: "अनार का तेलिया / जीवाणु झुलसा रोग (Teliya Rog)",
    description: "Dark oily brown spots on leaves, stems, and fruits forming 'L' shaped cracks on fruit skin.",
    description_hi: "अनार के फलों और पत्तियों पर तेल जैसे धब्बे (Teliya) तथा फलों का अंग्रेजी के 'L' आकार में फटना।",
    metadata: {
      crop: "Pomegranate / Anar",
      severity: "Very High",
      symptoms: "Water-soaked oily spots, cracking of pomegranates, black stem spots.",
      symptoms_hi: "फलों पर तैलीय धब्बे, अनार का बीच से फटना (L-shape crack).",
      organicTreatment: "Prune infected branches and apply Bordeaux paste on cut ends.",
      organicTreatment_hi: "कटे तनों पर बोर्डो लेप लगाएं। कॉपर फफूंदनाशी छिड़कें।",
      chemicalTreatment: "Streptocycline 0.5g/L + Copper Oxychloride 2.5g/L spray.",
      chemicalTreatment_hi: "स्ट्रैप्टोसाइक्लिन (0.5 ग्राम) + कॉपर ऑक्सीक्लोराइड (2.5 ग्राम/लीटर) का छिड़काव।",
      preventiveMeasures: "Maintain strict orchard sanitation and avoid overhead irrigation.",
      preventiveMeasures_hi: "ड्रिप सिंचाई अपनाएं, ऊपर से पानी न डालें।",
      keywords: ["pomegranate teliya", "anar teliya", "pomegranate bacterial blight"],
      keywords_hi: ["तेलिया रोग", "अनार तेलिया", "अनार फटना"],
      keywords_romanized: ["anar teliya", "pomegranate bacterial blight"]
    }
  },
  {
    id: "disease-grapes-downy-mildew",
    category: "disease",
    crop: "Grapes",
    topic: "Downy Mildew",
    title: "Grapes Downy Mildew (Angoor Mridu Romil / Peela Dhabba)",
    title_hi: "अंगूर का मृदु रोमिल आसिता (Downy Mildew)",
    description: "Translucent oily yellowish spots on upper leaf surface, white downy growth underneath.",
    description_hi: "पत्तियों की ऊपरी सतह पर तेल जैसे पीले धब्बे और निचली सतह पर सफेद रूई जैसा पाउडर।",
    metadata: {
      crop: "Grapes / Angoor",
      severity: "High",
      symptoms: "Oil-spot lesions on leaves, drying of grape clusters and berries.",
      symptoms_hi: "अंगूर के गुच्छे सूखना, पत्तियों की नीचे सफेद रोएं।",
      organicTreatment: "Spray Bordeaux mixture 1% preventively.",
      organicTreatment_hi: "बोर्डो मिश्रण (1%) का छिड़काव करें।",
      chemicalTreatment: "Copper hydroxide 77 WP at 2g/L or Dimethomorph 50 WP at 1g/L.",
      chemicalTreatment_hi: "डाइमेथोमोर्फ (1 ग्राम/लीटर) या कॉपर हाइड्रॉक्साइड का छिड़काव।",
      preventiveMeasures: "Prune canopy for proper air flow and sunlight.",
      preventiveMeasures_hi: "बेलों की छंटाई करके हवा और धूप का प्रवाह बनाएं।",
      keywords: ["grapes downy mildew", "angoor downy mildew", "grape oil spot"],
      keywords_hi: ["मृदु रोमिल अंगूर", "अंगूर रोग"],
      keywords_romanized: ["angoor downy mildew", "grapes disease"]
    }
  },
  {
    id: "disease-papaya-ring-spot",
    category: "disease",
    crop: "Papaya",
    topic: "Ring Spot Virus",
    title: "Papaya Ring Spot Virus (Papita Ring Spot Virus)",
    title_hi: "पपीते का रिंग स्पॉट वायरस (Ring Spot Virus)",
    description: "Yellow mosaic on leaves, dark green rings on fruits, and oily streaks on petioles.",
    description_hi: "पपीते की पत्तियों पर पीला मोज़ेक, फलों पर हरे गोल छल्ले (Rings) और डंठल पर तेल की धारियां।",
    metadata: {
      crop: "Papaya / Papita",
      severity: "High",
      symptoms: "Shoestring leaf symptoms, dark ring spots on fruits, low sugar content.",
      symptoms_hi: "पत्तियां धागे जैसी पतली होना, फलों पर गोल चकत्ते, मिठास कम होना।",
      organicTreatment: "Uproot infected trees. Control aphids with Neem oil 5ml/L.",
      organicTreatment_hi: "संक्रमित पौधों को उखाड़ दें। माहू नियंत्रण के लिए नीम तेल छिड़कें।",
      chemicalTreatment: "Imidacloprid 17.8 SL at 0.5 ml/L to suppress aphid vectors.",
      chemicalTreatment_hi: "इमिडाक्लोप्रिड (0.5 मिली/लीटर) का माहू (Aphid) नियंत्रण हेतु छिड़काव।",
      preventiveMeasures: "Plant border crops like maize or sorghum around papaya field.",
      preventiveMeasures_hi: "पपीते के खेत के चारों ओर मक्के की बॉर्डर फसल लगाएं।",
      keywords: ["papaya ring spot", "papita ring spot", "papaya leaf mosaic"],
      keywords_hi: ["रिंग स्पॉट", "पपीता मोज़ेक"],
      keywords_romanized: ["papita ring spot", "papaya ring spot"]
    }
  }
];

// Add 32 more diseases to reach 62+
const additionalDiseases = [
  { id: "disease-maize-maydis-blight", crop: "Maize", topic: "Maydis Blight", title: "Maize Maydis Leaf Blight", title_hi: "मक्का का मायडिस पत्ती झुलसा", desc: "Elongated rectangular brownish spots on maize leaves.", desc_hi: "मक्के की पत्तियों पर आयताकार भूरे धब्बे।" },
  { id: "disease-maize-turcicum-blight", crop: "Maize", topic: "Turcicum Blight", title: "Maize Turcicum Blight", title_hi: "मक्का का टरसिकाउम झुलसा", desc: "Long boat-shaped greyish-tan lesions on leaves.", desc_hi: "पत्तियों पर नाव के आकार के लंबे स्लेटी धब्बे।" },
  { id: "disease-maize-downy-mildew", crop: "Maize", topic: "Downy Mildew", title: "Maize Downy Mildew", title_hi: "मक्का का मृदु रोमिल आसिता", desc: "Yellowish striping on leaves with downy white fungus underneath.", desc_hi: "पत्तियों पर पीली धारियां और नीचे सफेद फफूंद।" },
  { id: "disease-rice-tungro", crop: "Rice", topic: "Tungro Virus", title: "Rice Tungro Virus", title_hi: "धान का टुंग्रो वायरस", desc: "Stunting, yellow-orange leaf discoloration transferred by leafhoppers.", desc_hi: "पौधा बौना होना, पत्तियां संतरी-पीली पड़ना।" },
  { id: "disease-rice-false-smut", crop: "Rice", topic: "False Smut", title: "Rice False Smut", title_hi: "धान का आभासी कगुआ", desc: "Individual rice grains turn into velvety yellow-orange balls.", desc_hi: "धान के दाने पीले-हरे मखमली गोलों में बदलना।" },
  { id: "disease-wheat-black-rust", crop: "Wheat", topic: "Black Rust", title: "Wheat Black Rust / Stem Rust", title_hi: "गेहूं का काला रतुआ (Stem Rust)", desc: "Dark reddish-brown elongated pustules on stems and leaf sheaths.", desc_hi: "तने और पत्तियों के आवरण पर लंबे काले-भूरे फफोले।" },
  { id: "disease-wheat-karnal-bunt", crop: "Wheat", topic: "Karnal Bunt", title: "Wheat Karnal Bunt", title_hi: "गेहूं का करनाल बंट", desc: "Partial conversion of grain into black powdery mass with fishy odor.", desc_hi: "दाने का आंशिक हिस्सा काले चूर्ण में बदलना, सड़ी मछली जैसी गंध।" },
  { id: "disease-soybean-rust", crop: "Soybean", topic: "Soybean Rust", title: "Soybean Rust", title_hi: "सोयाबीन का रतुआ रोग", desc: "Tiny reddish-brown pustules on underside of soybean leaves.", desc_hi: "सोयाबीन की पत्तियों की निचली सतह पर छोटे लाल-भूरे धब्बे।" },
  { id: "disease-soybean-yellow-mosaic", crop: "Soybean", topic: "Yellow Mosaic Virus", title: "Soybean Yellow Mosaic Virus", title_hi: "सोयाबीन पीला मोज़ेक वायरस", desc: "Bright yellow patches interspersed with green on soybean leaves.", desc_hi: "पत्तियों पर चमकीले पीले चकत्ते, पौधा बौना होना।" },
  { id: "disease-groundnut-tikka", crop: "Groundnut", topic: "Tikka Leaf Spot", title: "Groundnut Tikka Disease", title_hi: "मूंगफली का टिक्का रोग", desc: "Circular dark brown spots on leaf surfaces surrounded by yellow ring.", desc_hi: "पत्तियों पर गोल काले-भूरे धब्बे जिनके चारों ओर पीला घेरा होता है।" },
  { id: "disease-groundnut-collar-rot", crop: "Groundnut", topic: "Collar Rot", title: "Groundnut Collar Rot", title_hi: "मूंगफली का कॉलर रॉट / तना सड़न", desc: "Rotting of seedling hypocotyl at soil level covered with black spores.", desc_hi: "जमीन की सतह के पास तने का काला पड़कर सड़ जाना।" },
  { id: "disease-chickpea-ascochyta-blight", crop: "Chickpea", topic: "Ascochyta Blight", title: "Chickpea Ascochyta Blight", title_hi: "चने का एस्कोकाइटा झुलसा", desc: "Circular dark lesions with concentric dots on leaves and stems.", desc_hi: "पत्तियों और फलियों पर काले गोल धब्बे।" },
  { id: "disease-pigeonpea-sterility-mosaic", crop: "Pigeon Pea", topic: "Sterility Mosaic", title: "Pigeon Pea Sterility Mosaic", title_hi: "अरहर का बांझपन मोज़ेक रोग", desc: "Light green pale leaves, profuse vegetative growth, complete sterility.", desc_hi: "पत्तियां हल्की पीली, पौधे में फूल और फलियां न बनना।" },
  { id: "disease-sugarcane-smut", crop: "Sugarcane", topic: "Sugarcane Smut", title: "Sugarcane Smut", title_hi: "गन्ने का कगुआ / चाबुक रोग", desc: "Long whip-like black dusty structure arising from cane central shoot.", desc_hi: "गन्ने के शीर्ष से लंबी चाबुक जैसी काली संरचना निकलना।" },
  { id: "disease-sugarcane-grassy-shoot", crop: "Sugarcane", topic: "Grassy Shoot", title: "Sugarcane Grassy Shoot", title_hi: "गन्ने का घास सदृश रोह (Grassy Shoot)", desc: "Production of numerous pale yellow thin tillers giving a grassy look.", desc_hi: "गन्ने में अनगिनत पतले पीले कल्ले निकलना, घास जैसा दिखना।" },
  { id: "disease-banana-panama-wilt", crop: "Banana", topic: "Panama Wilt", title: "Banana Panama Wilt", title_hi: "केले का पनामा उकठा रोग", desc: "Yellowing of lower leaves along margins, longitudinal splitting of pseudostem.", desc_hi: "निचली पत्तियों का पीला पड़ना, तने का लंबाई में फटना।" },
  { id: "disease-grapes-powdery-mildew", crop: "Grapes", topic: "Powdery Mildew", title: "Grapes Powdery Mildew", title_hi: "अंगूर का चूर्णी फफूंद", desc: "White powdery patches on grape berries causing cracking.", desc_hi: "अंगूर के दानों पर सफेद पाउडर और दानों का फटना।" },
  { id: "disease-citrus-gummosis", crop: "Citrus", topic: "Citrus Gummosis", title: "Citrus Gummosis", title_hi: "नींबू का गोंदिया रोग (Gummosis)", desc: "Exudation of amber-colored gum from bark cracks of trunk.", desc_hi: "नींबू के तने की छाल से भूरा-पीला गोंद निकलना।" },
  { id: "disease-cabbage-black-rot", crop: "Cabbage", topic: "Black Rot", title: "Cabbage / Cauliflower Black Rot", title_hi: "गोभी का काला सड़न (Black Rot)", desc: "V-shaped yellow lesions on leaf margins with blackened leaf veins.", desc_hi: "पत्ती के किनारों पर V-आकार के पीले धब्बे, नसें काली होना।" },
  { id: "disease-pea-powdery-mildew", crop: "Pea", topic: "Powdery Mildew", title: "Pea Powdery Mildew", title_hi: "मटर का सफेद फफूंद / चूर्णी आसिता", desc: "Fluffy white powdery growth covering pea leaves and pods.", desc_hi: "मटर की पत्तियों और फलियों पर सफेद पाउडर की परत।" },
  { id: "disease-turmeric-leaf-spot", crop: "Turmeric", topic: "Leaf Spot", title: "Turmeric Leaf Spot", title_hi: "हल्दी का पत्ती धब्बा रोग", desc: "Elliptical brown spots on leaves with yellow halo.", desc_hi: "हल्दी के पत्तों पर बादामी रंग के लंबे धब्बे।" },
  { id: "disease-ginger-rhizome-rot", crop: "Ginger", topic: "Rhizome Rot", title: "Ginger Rhizome Rot / Soft Rot", title_hi: "अदरक का प्रकंद सड़न (Rhizome Rot)", desc: "Water-soaked rot of rhizome tissue at soil level causing foul smell.", desc_hi: "जमीन के नीचे अदरक की गांठों का सड़ना और बदबू आना।" },
  { id: "disease-brinjal-phomopsis", crop: "Brinjal", topic: "Phomopsis Blight", title: "Brinjal Phomopsis Blight", title_hi: "बैंगन का फोमोप्सिस झुलसा", desc: "Circular brown spots on leaves and soft watery decay of brinjal fruits.", desc_hi: "फलों का गलकर सड़ना और पत्तियों पर भूरे धब्बे।" },
  { id: "disease-brinjal-bacterial-wilt", crop: "Brinjal", topic: "Bacterial Wilt", title: "Brinjal Bacterial Wilt", title_hi: "बैंगन का जीवाणु उकठा", desc: "Rapid wilting of green brinjal plants without leaf yellowing.", desc_hi: "हरे पौधे का अचानक रातों-रात मुरझाना।" },
  { id: "disease-okra-powdery-mildew", crop: "Okra", topic: "Powdery Mildew", title: "Okra Powdery Mildew", title_hi: "भिंडी का सफेद फफूंद", desc: "White powdery patches on upper leaf surface of bhindi.", desc_hi: "भिंडी की पत्तियों के ऊपरी भाग पर सफेद चूर्ण।" },
  { id: "disease-onion-purple-blotch", crop: "Onion", topic: "Purple Blotch", title: "Onion Purple Blotch", title_hi: "प्याज़ का बैंगनी धब्बा रोग", desc: "Small water-soaked sunken lesions turning purple with yellow border.", desc_hi: "प्याज़ की पत्तियों पर बैंगनी रंग के धब्बे।" },
  { id: "disease-garlic-stemphylium-blight", crop: "Garlic", topic: "Stemphylium Blight", title: "Garlic Stemphylium Blight", title_hi: "लहसुन का स्टेमफिलियम झुलसा", desc: "Yellowish pale spots on leaves changing to purple or dark brown.", desc_hi: "लहसुन की पत्तियों की नोक पीली पड़कर सूखना।" },
  { id: "disease-cucumber-downy-mildew", crop: "Cucumber", topic: "Downy Mildew", title: "Cucumber Downy Mildew", title_hi: "खीरा/ककड़ी का मृदु रोमिल", desc: "Angular yellow spots on leaves bounded by leaf veins.", desc_hi: "पत्तियों पर नसों से घिरे कोणीय पीले धब्बे।" },
  { id: "disease-watermelon-fusarium-wilt", crop: "Watermelon", topic: "Fusarium Wilt", title: "Watermelon Fusarium Wilt", title_hi: "तरबूज का उकठा रोग", desc: "Wilting of runners and vines in watermelon fields.", desc_hi: "तरबूज की बेलों का अचानक सूखना।" },
  { id: "disease-papaya-anthracnose", crop: "Papaya", topic: "Anthracnose", title: "Papaya Anthracnose Fruit Rot", title_hi: "पपीते का एंथ्रेक्नोज फल सड़न", desc: "Sunken circular dark spots on ripe papaya skin.", desc_hi: "पके पपीते की छाल पर गोल धंसे हुए सड़े धब्बे।" },
  { id: "disease-apple-scab", crop: "Apple", topic: "Apple Scab", title: "Apple Scab", title_hi: "सेब का स्कैब रोग", desc: "Olive green velvety spots on apple leaves and fruit skin.", desc_hi: "सेब की छाल और पत्तियों पर जैतूनी भूरे खुरदरे धब्बे।" },
  { id: "disease-tea-blister-blight", crop: "Tea", topic: "Blister Blight", title: "Tea Blister Blight", title_hi: "चाय का ब्लिस्टर ब्लाइट", desc: "Translucent pinkish spots forming indented blisters on young tea shoots.", desc_hi: "चाय की कोमल पत्तियों पर गुलाबी छाले (Blister) पड़ना।" }
];

additionalDiseases.forEach(d => {
  diseases.push({
    id: d.id,
    category: "disease",
    crop: d.crop,
    topic: d.topic,
    title: d.title,
    title_hi: d.title_hi,
    description: d.desc,
    description_hi: d.desc_hi,
    metadata: {
      crop: d.crop,
      severity: "Medium-High",
      symptoms: d.desc,
      symptoms_hi: d.desc_hi,
      organicTreatment: "Spray Neem oil 5ml/L or Trichoderma viride 5g/L.",
      organicTreatment_hi: "नीम तेल (5 मिली/लीटर) या ट्राइकोड्रामा (5 ग्राम/लीटर) का छिड़काव करें।",
      chemicalTreatment: "Spray Mancozeb 75 WP (2g/L) or Copper Oxychloride (3g/L) as recommended.",
      chemicalTreatment_hi: "मैनकोज़ेब (2 ग्राम/लीटर) या कॉपर ऑक्सीक्लोराइड का छिड़काव करें।",
      preventiveMeasures: "Follow crop rotation and field sanitation.",
      preventiveMeasures_hi: "फसल चक्र अपनाएं और खेत साफ रखें।",
      keywords: [d.topic.toLowerCase(), d.crop.toLowerCase() + " disease", d.id.replace("disease-", "")],
      keywords_hi: [d.title_hi, d.crop + " रोग"],
      keywords_romanized: [d.crop.toLowerCase() + " bimari", d.topic.toLowerCase() + " disease"]
    }
  });
});

console.log("Total disease records generated:", diseases.length);
fs.writeFileSync(path.join(__dirname, '../database/diseases/diseases.json'), JSON.stringify(diseases, null, 2));
console.log("Successfully written to database/diseases/diseases.json");
